### ISSUE TITLE
Alt+Tab experience similar to Unity

### ISSUE THREAD

**Issue by jackpot51** [pop-os/gnome-shell-extension-alt-tab-raise-first-window#1]
Package and release this for Artful Pop

**Comment by cassidyjames** [comment]
Should also compare to what upstream is doing, this came out today https://didrocks.fr/2017/09/14/ubuntu-gnome-shell-in-artful-day-12/

**Comment by jackpot51** [comment]
I am going to debianize this

**Comment by jackpot51** [comment]
Finished debianizing: https://github.com/system76/alt-tab-raise-first-window/commit/83ff174294871aafae3b57f7b616bffd5eb8c48e

**Comment by jackpot51** [comment]
Built in staging
