### ISSUE TITLE
Does not work with Gnome 3.32

### ISSUE THREAD

**Issue by nxs-45** [pop-os/gnome-shell-extension-alt-tab-raise-first-window#4]
gnome-shell-extention-alt-tab-raise-first-window is a wonderful and helpful utility. It is a utility I consider a must have. Unfortunately it no longer works on Gnome 3.32. Is there a update planned for Gnome 3.32? Thank you so much for your contribution to the esthetic and functionality of Gnome.

**Comment by brs17** [comment]
- [x] 19.04
- [x] 18.10
- [ ] 18.04
