### ISSUE TITLE
Windows keep grouped even disable the extension

### ISSUE THREAD

**Issue by iChunyu** [pop-os/gnome-shell-extension-alt-tab-raise-first-window#6]
Hello there, I want to show all windows when I press `alt` + `tab`, so I disabled the extension 'Alt tab: raise first window' in 'gnome-tweak-tools'. But it seems not work to me. Windows keep grouped when pressing `alt` + `tab`.

Am I did something wrong? (sorry, I'm new to Linux)

**Comment by jacobgkau** [comment]
GNOME Tweaks (formerly GNOME Tweak Tools) is no longer able to enable/disable extensions. Please use the Extensions app (green icon) instead.

I can confirm this behavior in GNOME Tweaks, and that disabling is possible via Extensions, so I am closing this issue. If the Extensions app doesn't work to disable the extension, please let us know and we can re-open.

An upstream merge request has removed the broken extensions page from GNOME Tweaks, so the next Tweaks release will not have that page: https://gitlab.gnome.org/GNOME/gnome-tweaks/-/merge_requests/50

**Comment by iChunyu** [comment]
Thanks for your advice. 



But when I turned off the alt-tab extension from the green-icon Extension app, it still doesn't work to show all windows.&nbsp;








------------------&nbsp;Original&nbsp;------------------
